spring.application.name: toby-spring-boot

logging:
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

my-server:
  context-path: /api
  port: 9090

data-source:
  driverClassName: org.h2.Driver
  url: "jdbc:h2:mem:"
  username: sa
  password: ''
