spring.application.name: toby-spring-boot

logging:
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:%5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 9090
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:"
    username: sa
    password: ''

